### ISSUE TITLE
Problem with MacOS, Node 16 and probably VIS

### ISSUE THREAD

**Issue by gaudes** [AlCalzone/create-adapter#834] opened 2021-10-03 13:16 UTC
Hi,

I'm trying to update an Adapter. Due to errors in workflow with MacOS and Node 16, I've build a test from scratch.

The repo is here.
https://github.com/gaudes/slideshowtest

All tests in the "test-and-release" workflow succeed, except MacOS with Node 16 with this error:

```
2021-10-03T13:10:53.540Z testing:integration:AdapterSetup Copying adapter files to test directory...
2021-10-03T13:10:54.327Z testing:integration:AdapterSetup Saving the adapter in package.json
2021-10-03T13:10:54.329Z testing:integration:AdapterSetup Deleting old remains of this adapter
2021-10-03T13:10:54.329Z testing:integration:AdapterSetup   => done!
2021-10-03T13:10:54.329Z testing:integration:ControllerSetup Testing if JS-Controller is installed...
2021-10-03T13:10:54.329Z testing:integration:ControllerSetup   => false
2021-10-03T13:10:54.648Z testing:integration:ControllerSetup   => false
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test-iobroker.slideshowupdate/node_modules/iobroker.vis
npm ERR! command failed
npm ERR! command sh -c node main.js --install
npm ERR! /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test-iobroker.slideshowupdate/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:164
npm ERR!         throw new Error(`Cannot find ${configFileName}`);
npm ERR!         ^
npm ERR! 
npm ERR! Error: Cannot find /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test-iobroker.slideshowupdate/iobroker-data/iobroker.json
npm ERR!     at new Adapter (/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test-iobroker.slideshowupdate/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:164:15)
npm ERR!     at Object.<anonymous> (/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test-iobroker.slideshowupdate/node_modules/iobroker.vis/main.js:20:24)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    1) "before all" hook for "The adapter starts"
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
npm ERR!     at node:internal/main/run_main_module:17:47


npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/runner/.npm/_logs/2021-10-03T13_11_17_367Z-debug.log
  0 passing (24s)
```

Any ideas ?

Thanks and regards,
Ralf

**Comment by AlCalzone** [comment] 2021-10-15 13:26
We're seeing randomly failing builds on MacOS in other projects too. Sometimes they work, sometimes not.
Not sure if this is actually related to the adapter.

**Comment by gaudes** [comment] 2021-11-02 20:14
Hi,

so there are currently two possibilities:

- Remove MacOS from the matrix
- Remove support for node 16.x

I would prefere removing node 16.x

Any general recommendations ?

Thanks and kind regards,

Ralf

**Comment by AlCalzone** [comment] 2021-11-02 20:42
Are you using any weird native modules? I'm having no problems, except node 16/Windows which has been failing since yesterday sporadically

**Comment by Apollon77** [comment] 2021-11-03 22:25
I think the issue is the same as we found out in the corresponding npm issue ...It is all about how npm 7 executes stff. maybe downgrade of npm to 6 works ?

**Comment by UncleSamSwiss** [comment] 2021-11-23 15:56
The solution for now is not to use npm 7.
create-adapter and all other tools will support npm 7 once we have found and implemented a solution to this problem.

There is nothing create-adapter can do, thus closing this issue.

**Closed as completed by UncleSamSwiss** 2021-11-23 15:56 UTC

**Comment by Apollon77** [comment] 2022-01-29 22:29
sith npm 7/8 and so it should work

**Comment by AlCalzone** [comment] 2022-01-30 07:56
> sith

Join the dark side. We have 🍪🍪...

**Comment by Apollon77** [comment] 2022-01-30 08:31
;-)
